import {ReactNode} from 'react';

export type PBoxProps = {
  children?: ReactNode;
  className?: string | null;
  onClick?: (e: any) => void;
} & StylesProps;

export type StylesProps = {
  id?: string;
  display?: 'grid' | 'flex' | 'block' | 'inline-block' | 'none';
  position?: 'fixed' | 'absolute' | 'relative' | 'sticky';
  top?: string;
  left?: string;
  bottom?: string;
  right?: string;
  transform?: string;
  transition?: string;
  zIndex?: number;
  gridTemplateColumns?: string;
  gap?: string;
  flexDirection?: 'column' | 'row';
  flexWrap?: 'wrap' | 'nowrap';
  flex?: string;
  gridTemplateRows?: string;
  justifySelf?: 'start' | 'end' | 'center' | 'stretch';
  alignSelf?: 'start' | 'end' | 'center' | 'stretch';
  alignItems?: 'start' | 'end' | 'center' | 'stretch' | 'baseline';
  justifyItems?: 'start' | 'end' | 'center' | 'stretch';
  justifyContent?: 'start' | 'end' | 'center' | 'stretch' | 'space-around' | 'space-between' | 'space-evenly';
  alignContent?: 'start' | 'end' | 'center' | 'stretch' | 'space-around' | 'space-between' | 'space-evenly';
  gridAutoFlow?: 'row' | 'column' | 'row dense' | 'column dense';
  padding?: string;
  paddingTop?: string;
  paddingLeft?: string;
  paddingRight?: string;
  paddingBottom?: string;
  paddingX?: string;
  paddingY?: string;
  margin?: string;
  marginTop?: string;
  marginLeft?: string;
  marginRight?: string;
  marginBottom?: string;
  width?: string;
  minWidth?: string;
  maxWidth?: string;
  borderRadius?: string;
  borderTop?: string;
  borderBottom?: string;
  borderLeft?: string;
  borderRight?: string;
  borderBottomLeftRadius?: string;
  borderBottomRightRadius?: string;
  overflow?: 'hidden' | 'auto';
  height?: string;
  minHeight?: string;
  maxHeight?: string;
  textAlign?: 'center' | 'left' | 'right';
  cursor?: 'pointer' | 'default' | 'not-allowed';
  boxShadow?: string;
  outline?: string;
  opacity?: number;
  pointerEvents?: 'none' | 'inherit';
  visibility?: 'visible' | 'hidden';
};
