export const ABI_721 = [
  {
    inputs: [{internalType: 'address', name: '_marketplaceAddress', type: 'address'}],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'owner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'approved', type: 'address'},
      {indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256'},
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'owner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'operator', type: 'address'},
      {indexed: false, internalType: 'bool', name: 'approved', type: 'bool'},
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{indexed: false, internalType: 'uint256', name: 'nftID', type: 'uint256'}],
    name: 'Burned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{indexed: false, internalType: 'uint256', name: 'nftID', type: 'uint256'}],
    name: 'Minted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'previousOwner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'from', type: 'address'},
      {indexed: true, internalType: 'address', name: 'to', type: 'address'},
      {indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256'},
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    inputs: [
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'owner', type: 'address'}],
    name: 'balanceOf',
    outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'nftId', type: 'uint256'}],
    name: 'burn',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'tokenId', type: 'uint256'}],
    name: 'getApproved',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'owner', type: 'address'},
      {internalType: 'address', name: 'operator', type: 'address'},
    ],
    name: 'isApprovedForAll',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'marketplaceAddress',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'string', name: 'tokenURI', type: 'string'},
      {internalType: 'uint256', name: 'royaltyPercentage', type: 'uint256'},
    ],
    name: 'mint',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'tokenId', type: 'uint256'}],
    name: 'ownerOf',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function'},
  {
    inputs: [
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
      {internalType: 'uint256', name: 'saleValue', type: 'uint256'},
    ],
    name: 'royaltyInfo',
    outputs: [
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'uint256', name: '', type: 'uint256'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'from', type: 'address'},
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // {
  //   inputs: [
  //     {internalType: 'address', name: 'from', type: 'address'},
  //     {internalType: 'address', name: 'to', type: 'address'},
  //     {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
  //     {internalType: 'bytes', name: '_data', type: 'bytes'},
  //   ],
  //   name: 'safeTransferFrom',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  {
    inputs: [
      {internalType: 'address', name: 'operator', type: 'address'},
      {internalType: 'bool', name: 'approved', type: 'bool'},
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: '_marketplaceAddress', type: 'address'}],
    name: 'setMarketplaceAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
      {internalType: 'string', name: 'tokenURI', type: 'string'},
    ],
    name: 'setTokenURI',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'bytes4', name: 'interfaceId', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'tokenId', type: 'uint256'}],
    name: 'tokenURI',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{internalType: 'uint256', name: '_value', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'from', type: 'address'},
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export const ABI_1155 = [
  {
    inputs: [{internalType: 'address', name: '_marketplaceAddress', type: 'address'}],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'account', type: 'address'},
      {indexed: true, internalType: 'address', name: 'operator', type: 'address'},
      {indexed: false, internalType: 'bool', name: 'approved', type: 'bool'},
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: false, internalType: 'uint256[]', name: 'nftIds', type: 'uint256[]'},
      {indexed: false, internalType: 'uint256[]', name: 'amounts', type: 'uint256[]'},
    ],
    name: 'BatchBurned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: false, internalType: 'uint256[]', name: 'nftIds', type: 'uint256[]'},
      {indexed: false, internalType: 'uint256[]', name: 'amounts', type: 'uint256[]'},
    ],
    name: 'BatchMinted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'previousOwner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: false, internalType: 'uint256', name: 'nftId', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256'},
    ],
    name: 'SingleBurned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: false, internalType: 'uint256', name: 'nftId', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'quantity', type: 'uint256'},
    ],
    name: 'SingleMinted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'operator', type: 'address'},
      {indexed: true, internalType: 'address', name: 'from', type: 'address'},
      {indexed: true, internalType: 'address', name: 'to', type: 'address'},
      {indexed: false, internalType: 'uint256[]', name: 'ids', type: 'uint256[]'},
      {indexed: false, internalType: 'uint256[]', name: 'values', type: 'uint256[]'},
    ],
    name: 'TransferBatch',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'operator', type: 'address'},
      {indexed: true, internalType: 'address', name: 'from', type: 'address'},
      {indexed: true, internalType: 'address', name: 'to', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'id', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'value', type: 'uint256'},
    ],
    name: 'TransferSingle',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: false, internalType: 'string', name: 'value', type: 'string'},
      {indexed: true, internalType: 'uint256', name: 'id', type: 'uint256'},
    ],
    name: 'URI',
    type: 'event',
  },
  {
    inputs: [
      {internalType: 'address', name: 'account', type: 'address'},
      {internalType: 'uint256', name: 'id', type: 'uint256'},
    ],
    name: 'balanceOf',
    outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address[]', name: 'accounts', type: 'address[]'},
      {internalType: 'uint256[]', name: 'ids', type: 'uint256[]'},
    ],
    name: 'balanceOfBatch',
    outputs: [{internalType: 'uint256[]', name: '', type: 'uint256[]'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'uint256', name: 'nftId', type: 'uint256'},
      {internalType: 'uint256', name: 'amount', type: 'uint256'},
    ],
    name: 'burn',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'uint256[]', name: 'nftIds', type: 'uint256[]'},
      {internalType: 'uint256[]', name: 'amounts', type: 'uint256[]'},
    ],
    name: 'burnBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'account', type: 'address'},
      {internalType: 'address', name: 'operator', type: 'address'},
    ],
    name: 'isApprovedForAll',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'marketplaceAddress',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'string', name: 'URI', type: 'string'},
      {internalType: 'uint256', name: 'royaltyPercentage', type: 'uint256'},
      {internalType: 'uint256', name: 'quantity', type: 'uint256'},
    ],
    name: 'mint',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'string[]', name: 'tokenURIs', type: 'string[]'},
      {internalType: 'uint256', name: 'royaltyPercentage', type: 'uint256'},
      {internalType: 'uint256[]', name: '_quantities', type: 'uint256[]'},
    ],
    name: 'mintBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
    name: 'quantities',
    outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function'},
  {
    inputs: [
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
      {internalType: 'uint256', name: 'saleValue', type: 'uint256'},
    ],
    name: 'royaltyInfo',
    outputs: [
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'uint256', name: '', type: 'uint256'},
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'from', type: 'address'},
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256[]', name: 'ids', type: 'uint256[]'},
      {internalType: 'uint256[]', name: 'amounts', type: 'uint256[]'},
      {internalType: 'bytes', name: 'data', type: 'bytes'},
    ],
    name: 'safeBatchTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'from', type: 'address'},
      {internalType: 'address', name: 'to', type: 'address'},
      {internalType: 'uint256', name: 'id', type: 'uint256'},
      {internalType: 'uint256', name: 'amount', type: 'uint256'},
      {internalType: 'bytes', name: 'data', type: 'bytes'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'operator', type: 'address'},
      {internalType: 'bool', name: 'approved', type: 'bool'},
    ],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: '_marketplaceAddress', type: 'address'}],
    name: 'setMarketplaceAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'bytes4', name: 'interfaceId', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{internalType: 'bool', name: '', type: 'bool'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{internalType: 'uint256', name: '_value', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'tokenId', type: 'uint256'}],
    name: 'uri',
    outputs: [{internalType: 'string', name: '', type: 'string'}],
    stateMutability: 'view',
    type: 'function',
  },
];

export const ABI_MARKET = [
  {
    inputs: [
      {internalType: 'address', name: 'feeAddress_', type: 'address'},
      {internalType: 'uint256', name: 'feePercentage_', type: 'uint256'},
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [{indexed: true, internalType: 'uint256', name: 'itemId', type: 'uint256'}],
    name: 'MarketItemClosed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'uint256', name: 'itemId', type: 'uint256'},
      {indexed: true, internalType: 'address', name: 'nftContract', type: 'address'},
      {indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256'},
      {indexed: false, internalType: 'address', name: 'seller', type: 'address'},
      {indexed: false, internalType: 'address', name: 'owner', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'price', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'quantity', type: 'uint256'},
      {indexed: false, internalType: 'enum StarMarketDemo.TokenType', name: 'tokenType', type: 'uint8'},
    ],
    name: 'MarketItemCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'uint256', name: 'itemId', type: 'uint256'},
      {indexed: true, internalType: 'address', name: 'sender', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256'},
    ],
    name: 'MarketNFTSold',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'previousOwner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'uint256', name: 'itemId', type: 'uint256'},
      {indexed: false, internalType: 'uint256', name: 'newPrice', type: 'uint256'},
    ],
    name: 'PriceChanged',
    type: 'event',
  },
  {
    inputs: [
      {internalType: 'uint256', name: 'itemId', type: 'uint256'},
      {internalType: 'uint256', name: 'quantityToBuy', type: 'uint256'},
    ],
    name: 'buyMarketItem1155',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'itemId', type: 'uint256'}],
    name: 'buyMarketItem721',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'itemId', type: 'uint256'}],
    name: 'closeMarketItem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'nftContract', type: 'address'},
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
      {internalType: 'uint256', name: 'price', type: 'uint256'},
      {internalType: 'uint256', name: 'quantity', type: 'uint256'},
    ],
    name: 'createMarketItem1155',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: 'nftContract', type: 'address'},
      {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
      {internalType: 'uint256', name: 'price', type: 'uint256'},
    ],
    name: 'createMarketItem721',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'uint256', name: 'itemId', type: 'uint256'},
      {internalType: 'uint256', name: 'newPrice', type: 'uint256'},
    ],
    name: 'editMarketItem',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feeAddress',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feePercentage',
    outputs: [{internalType: 'uint256', name: '', type: 'uint256'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: 'marketItemId', type: 'uint256'}],
    name: 'getMarketItem',
    outputs: [
      {
        components: [
          {internalType: 'uint256', name: 'itemId', type: 'uint256'},
          {internalType: 'address', name: 'nftContract', type: 'address'},
          {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
          {internalType: 'address', name: 'seller', type: 'address'},
          {internalType: 'address', name: 'owner', type: 'address'},
          {internalType: 'uint256', name: 'price', type: 'uint256'},
          {internalType: 'uint256', name: 'quantity', type: 'uint256'},
          {internalType: 'enum StarMarketDemo.TokenType', name: 'tokenType', type: 'uint8'},
          {internalType: 'enum StarMarketDemo.MarketStatus', name: 'status', type: 'uint8'},
        ],
        internalType: 'struct StarMarketDemo.MarketItem',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMarketItems',
    outputs: [
      {
        components: [
          {internalType: 'uint256', name: 'itemId', type: 'uint256'},
          {internalType: 'address', name: 'nftContract', type: 'address'},
          {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
          {internalType: 'address', name: 'seller', type: 'address'},
          {internalType: 'address', name: 'owner', type: 'address'},
          {internalType: 'uint256', name: 'price', type: 'uint256'},
          {internalType: 'uint256', name: 'quantity', type: 'uint256'},
          {internalType: 'enum StarMarketDemo.TokenType', name: 'tokenType', type: 'uint8'},
          {internalType: 'enum StarMarketDemo.MarketStatus', name: 'status', type: 'uint8'},
        ],
        internalType: 'struct StarMarketDemo.MarketItem[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'walletAddress', type: 'address'}],
    name: 'getUserItems',
    outputs: [
      {
        components: [
          {internalType: 'uint256', name: 'itemId', type: 'uint256'},
          {internalType: 'address', name: 'nftContract', type: 'address'},
          {internalType: 'uint256', name: 'tokenId', type: 'uint256'},
          {internalType: 'address', name: 'seller', type: 'address'},
          {internalType: 'address', name: 'owner', type: 'address'},
          {internalType: 'uint256', name: 'price', type: 'uint256'},
          {internalType: 'uint256', name: 'quantity', type: 'uint256'},
          {internalType: 'enum StarMarketDemo.TokenType', name: 'tokenType', type: 'uint8'},
          {internalType: 'enum StarMarketDemo.MarketStatus', name: 'status', type: 'uint8'},
        ],
        internalType: 'struct StarMarketDemo.MarketItem[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'marketOwner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'uint256', name: '', type: 'uint256'},
      {internalType: 'uint256', name: '', type: 'uint256'},
      {internalType: 'bytes', name: '', type: 'bytes'},
    ],
    name: 'onERC1155Received',
    outputs: [{internalType: 'bytes4', name: '', type: 'bytes4'}],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'address', name: '', type: 'address'},
      {internalType: 'uint256', name: '', type: 'uint256'},
      {internalType: 'bytes', name: '', type: 'bytes'},
    ],
    name: 'onERC721Received',
    outputs: [{internalType: 'bytes4', name: '', type: 'bytes4'}],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function'},
  {
    inputs: [{internalType: 'address', name: '_feeAddress', type: 'address'}],
    name: 'setFeeAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'uint256', name: '_feePercentage', type: 'uint256'}],
    name: 'setFeePercentage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
